name: Build and Test macOS App

on:
  push:
    tags:
      - 'v*'  # Triggers on any tag starting with 'v'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install PySide6

    - name: Create .spec file
      run: |
        echo """
        # -*- mode: python ; coding: utf-8 -*-
        
        block_cipher = None
        
        a = Analysis(
            ['main.py'],
            pathex=[],
            binaries=[],
            datas=[],
            hiddenimports=['PySide6.QtCore', 'PySide6.QtWidgets', 'PySide6.QtGui'],
            hookspath=[],
            hooksconfig={},
            runtime_hooks=[],
            excludes=['matplotlib', 'numpy', 'PIL'],
            win_no_prefer_redirects=False,
            win_private_assemblies=False,
            cipher=block_cipher,
            noarchive=False,
        )
        
        pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
        
        exe = EXE(
            pyz,
            a.scripts,
            a.binaries,
            a.zipfiles,
            a.datas,
            [],
            name='HelloWorld',
            debug=False,
            bootloader_ignore_signals=False,
            strip=False,
            upx=True,
            upx_exclude=[],
            runtime_tmpdir=None,
            console=False,
            disable_windowed_traceback=False,
            argv_emulation=True,
            target_arch='universal2'
        )
        """ > HelloWorld.spec

    - name: Create Info.plist
      run: |
        echo """<?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>HelloWorld</string>
            <key>CFBundleIdentifier</key>
            <string>com.example.helloworld</string>
            <key>CFBundleName</key>
            <string>HelloWorld</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0</string>
            <key>LSMinimumSystemVersion</key>
            <string>10.13</string>
            <key>NSHighResolutionCapable</key>
            <true/>
            <key>LSArchitecturePriority</key>
            <array>
                <string>arm64</string>
                <string>x86_64</string>
            </array>
        </dict>
        </plist>""" > Info.plist

    - name: Build App
      run: |
        pyinstaller HelloWorld.spec
        mkdir -p "dist/HelloWorld.app/Contents/MacOS"
        mkdir -p "dist/HelloWorld.app/Contents/Resources"
        cp Info.plist "dist/HelloWorld.app/Contents/"
        mv "dist/HelloWorld" "dist/HelloWorld.app/Contents/MacOS/"

    - name: Create DMG
      run: |
        hdiutil create -volname "HelloWorld" -srcfolder "dist/HelloWorld.app" -ov -format UDZO "dist/HelloWorld.dmg"

    # Add this step to upload the artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: HelloWorld-macOS
        path: |
          dist/HelloWorld.dmg
          dist/HelloWorld.app

  test:
    needs: build
    runs-on: macos-latest

    steps:
    - name: Download built artifacts
      uses: actions/download-artifact@v3
      with:
        name: HelloWorld-macOS
        path: download

    - name: List downloaded files
      run: ls -R download

    - name: Test Installation
      run: |
        # Mount the DMG
        hdiutil attach download/HelloWorld.dmg
        
        # Test if the app exists
        if [ ! -d "/Volumes/HelloWorld/HelloWorld.app" ]; then
          echo "❌ App not found in DMG"
          exit 1
        fi
        
        # Copy to Applications
        mkdir -p ~/Applications
        cp -r "/Volumes/HelloWorld/HelloWorld.app" ~/Applications/
        
        # Unmount DMG
        hdiutil detach "/Volumes/HelloWorld"
        
        # Try to run
        echo "📱 Attempting to launch app..."
        open ~/Applications/HelloWorld.app || {
          echo "❌ Failed to open app"
          exit 1
        }
        
        # Check if running
        sleep 5
        if pgrep -f "HelloWorld" > /dev/null; then
          echo "✅ App launched successfully!"
        else
          echo "❌ App failed to launch"
          exit 1
        fi

    - name: Clean up
      if: always()
      run: |
        rm -rf ~/Applications/HelloWorld.app

    - name: Create Release
      if: success()
      uses: softprops/action-gh-release@v1
      with:
        files: |
          download/HelloWorld.dmg
        name: Release ${{ github.ref_name }}
        body: |
          HelloWorld App Release ${{ github.ref_name }}
          - Successfully built and tested on macOS
          - Universal binary (supports both Intel and M1 Macs)