name: Build macOS DMG

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PySide6
        pip install pyinstaller
        brew install create-dmg

    - name: Build application
      run: |
        pyinstaller HelloWorld.spec

    - name: Create DMG
      run: |
        mkdir dmg_contents
        cp -r "dist/HelloWorld.app" dmg_contents/
        
        create-dmg \
          --volname "HelloWorld" \
          --window-pos 200 120 \
          --window-size 600 400 \
          --icon-size 100 \
          --icon "HelloWorld.app" 200 190 \
          --hide-extension "HelloWorld.app" \
          --app-drop-link 400 190 \
          "HelloWorld.dmg" \
          "dmg_contents/"

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "v${{ github.run_number }}" \
          --title "Release v${{ github.run_number }}" \
          --notes "Universal macOS build (Intel + Apple Silicon)" \
          HelloWorld.dmg