name: Build and Test macOS App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install PySide6

    - name: Create Bundle Script
      run: |
        echo """
        import PyInstaller.__main__
        
        PyInstaller.__main__.run([
            '--name=HelloWorld',
            '--windowed',
            '--onedir',
            '--noconfirm',
            '--clean',
            '--collect-binaries=PySide6',
            '--collect-data=PySide6',
            '--hidden-import=PySide6.QtCore',
            '--hidden-import=PySide6.QtGui',
            '--hidden-import=PySide6.QtWidgets',
            '--hidden-import=PySide6.QtQml',
            '--add-binary=/Library/Frameworks/Python.framework/Versions/3.10/Python:Python.framework/Versions/3.10/Python',
            'main.py'
        ])
        """ > bundle.py

    - name: Create Info.plist
      run: |
        echo """<?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>HelloWorld</string>
            <key>CFBundleIdentifier</key>
            <string>com.example.helloworld</string>
            <key>CFBundleName</key>
            <string>HelloWorld</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0</string>
            <key>LSMinimumSystemVersion</key>
            <string>10.13</string>
            <key>NSHighResolutionCapable</key>
            <true/>
            <key>CFBundleSupportedPlatforms</key>
            <array>
                <string>MacOSX</string>
            </array>
            <key>LSArchitecturePriority</key>
            <array>
                <string>arm64</string>
                <string>x86_64</string>
            </array>
        </dict>
        </plist>""" > Info.plist

    - name: Build App
      run: |
        # Build using Python script
        python bundle.py
        
        # Setup proper bundle structure
        mkdir -p "dist/HelloWorld.app/Contents/Frameworks"
        mkdir -p "dist/HelloWorld.app/Contents/MacOS"
        
        # Copy Python framework
        cp -R /Library/Frameworks/Python.framework "dist/HelloWorld.app/Contents/Frameworks/"
        
        # Copy Info.plist
        cp Info.plist "dist/HelloWorld.app/Contents/"
        
        # Copy everything from dist/HelloWorld to MacOS
        cp -R dist/HelloWorld/* "dist/HelloWorld.app/Contents/MacOS/"
        
        # Set permissions
        chmod +x "dist/HelloWorld.app/Contents/MacOS/HelloWorld"
        
        # Fix framework links
        install_name_tool -change /Library/Frameworks/Python.framework/Versions/3.10/Python @executable_path/../Frameworks/Python.framework/Versions/3.10/Python "dist/HelloWorld.app/Contents/MacOS/HelloWorld"

    - name: Create DMG
      run: |
        hdiutil create -volname "HelloWorld" -srcfolder "dist/HelloWorld.app" -ov -format UDZO "dist/HelloWorld.dmg"

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: HelloWorld-macOS
        path: |
          dist/HelloWorld.dmg
          dist/HelloWorld.app

  test:
    needs: build
    runs-on: macos-latest

    steps:
    - name: Download built artifacts
      uses: actions/download-artifact@v3
      with:
        name: HelloWorld-macOS
        path: download

    - name: Test Installation
      run: |
        # Mount DMG
        hdiutil attach download/HelloWorld.dmg
        
        # Debug - Check app contents
        echo "Checking app structure..."
        ls -la "/Volumes/HelloWorld/HelloWorld.app/Contents/Frameworks" || true
        ls -la "/Volumes/HelloWorld/HelloWorld.app/Contents/MacOS" || true
        
        # Copy to Applications
        mkdir -p ~/Applications
        cp -R "/Volumes/HelloWorld/HelloWorld.app" ~/Applications/
        
        # Set permissions
        chmod +x ~/Applications/HelloWorld.app/Contents/MacOS/HelloWorld
        
        # Unmount DMG
        hdiutil detach "/Volumes/HelloWorld"
        
        # Try to run with debug output
        echo "📱 Attempting to launch app..."
        open ~/Applications/HelloWorld.app
        
        # Wait and check process
        sleep 5
        ps aux | grep HelloWorld
        
        # Check if running
        if pgrep -f "HelloWorld" > /dev/null; then
          echo "✅ App launched successfully!"
        else
          echo "❌ App failed to launch"
          # Print logs if available
          echo "System logs:"
          log show --predicate 'processImagePath contains "HelloWorld"' --last 1m
          exit 1
        fi

    - name: Create Release
      if: success()
      uses: softprops/action-gh-release@v1
      with:
        files: download/HelloWorld.dmg
        name: Release ${{ github.ref_name }}
        body: |
          HelloWorld App Release ${{ github.ref_name }}
          - Universal binary (supports both Intel and M1 Macs)